server:
  port: 8081

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/rowitech_auth
    password: koberflow
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

